### ISSUE TITLE
Edit loadout button broken in 10.2

### ISSUE THREAD

**Issue by cremor** [NumyAddon/TalentTreeTweaks#28]
After patch 10.2 the edit button for the talent loadout is broken. When I click it, no dialog is opened but instead the loadout vanishes from the list.

When I disable the Talent Tree Tweaks addon the button works correctly again.

Here is an screenshot after I clicked the button on 3 loadouts:
![grafik](https://github.com/NumyAddon/TalentTreeTweaks/assets/116314/93fd5423-e9c1-4e92-b530-7e3b991eafe8)

**Comment by voidzone** [comment]
Having the same issue with v1.10.5 of the addon.
No errors are being triggerd

**Comment by Numynum** [comment]
I'm seeing the same thing, will look into it tomorrow :)

**Comment by Numynum** [comment]
turns out there was a problem in the DropDown lib I use, fixed now

**Comment by cremor** [comment]
@Numynum I've updated to v1.10.6 and it's fixed for most talent loadouts. But the very first loadout in the list still shows the same issue.

**Comment by Numynum** [comment]
odd, it's working fine for me
is it also broken with all other addons disabled?

**Comment by cremor** [comment]
Not, it indeed works fine with only Talent Tree Tweaks loaded.
I couldn't yet figure out which specific other addon triggers the bug. I first suspected other addons using LibUIDropDownMenu but it looks like that's not it.

**Comment by adispen** [comment]
Seems like addons with broken version of the LibUIDropDownMenu library were the culprit for me @cremor . Modifying LibUIDropDownMenu.lua [per this issue](https://legacy.curseforge.com/wow/addons/libuidropdownmenu/issues/17) in each of their local library files resolved it. The culprits in my specific case were AngryKeystones, TwitchEmotes, and RareScanner. Don't think there's anything else to be done on your end @Numynum just need those addon authors to fix. Appreciate your work!

**Comment by cremor** [comment]
But shouldn't the updated version inside TalentTreeTweaks replace the old lib version in all addons automatically? Unless the modifications done by @Numynum to the lib prevent that.

**Comment by Numynum** [comment]
Yeah, seems I rushed out the fix a bit too quickly 🙂 
I might find some time to fix it properly today, but might have to wait for tomorrow
(I decided to fork the library, and thought I changed all the shared variables to something unique, but clearly I missed some; didn't have the time to test with an addon using the original lib)

**Comment by Numynum** [comment]
should be fixed properly now
